COUNT_POV_CLASSES = 9
COUNT_MARKER = 8
BATCH_SIZE = 512

INPUT_SIZE = 17  # number of features
HIDDEN_SIZE = 128  # number of features in hidden state
NUM_LAYERS = 1
NUM_CLASSES_BASE = 8  # number of output classes

LOSS_OUT = 9
ENTROPY_OUT = 9
SINGLE_MARKER_OUT = 8
EACH_POV_MARKER_OUT = 72

NUM_CLASSES_IG = 26
NUM_CLASSES_IG_MARKER_POV = 98

